/**
 * Vietnamese translations for all Bandersnatch interactive choice text.
 * Translated from BandersnatchInteractive-master/assets/choices/en.js
 * Structure: { [segmentId]: { [choiceId]: "Vietnamese text" } }
 */
export const VI: Record<string, Record<string, string>> = {
  "2G": { "1R": "PHAEDRA", "1S": "TAM GIÁC BERMUDA" },
  "3AF2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3AF1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "SS20": { "R5": "GẶP BÁC SĨ HAYNES", "3Nx": "QUAY LẠI" },
  "SS21": { "R6": "'CHƯƠNG TRÌNH & KIỂM SOÁT'", "5H": "GIẾT BỐ" },
  "SS22": { "nsg-WhoThereChoice": "AI ĐÓ VẬY?", "5H": "GIẾT BỐ" },
  "2Bp2": { "No": "KHÔNG" },
  "3Xcd": { "nsg-ThrowThemChoice": "VỨTCHÚNG ĐI", "nsg-FlushThemChoice3X": "THẢI XUỐNG BỒN" },
  "2Bp1": { "No": "KHÔNG", "3B": "NÉM TRÀ VÀO MÁY TÍNH", "3C": "LA MẮNG BỐ" },
  "Z62f": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3Vx": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "S44A": { "R3": "NÓI VỀ MẸ", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "Z62e": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "S44B": { "R3": "NÓI VỀ MẸ", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "Z62d": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "7D": { "Yeah": "CÓ", "FYeah": "CÓ ĐỂU ĐÓ!", "7L": "NHẢY QUA CỬA SỔ", "7H": "ĐÁNH NHAU VỚI CÔ TA" },
  "Z62c": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3Vff": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "1H": { "nsg-8AChoice": "CHẤP NHẬN", "nsg-1Qnw-1Qtt": "TỪ CHỐI" },
  "ZQ": { "nsg-FamilyPhotoChoice": "NHẶT ẢNH GIA ĐÌNH", "nsg-BookChoice": "NHẶT QUYỂN SÁCH" },
  "1G": { "nsg-8AChoice": "CHẤP NHẬN", "nsg-1Qnw-1Qtt": "TỪ CHỐI" },
  "ZP": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "5AG2": { "5AH": "ĐỂ ANH TA ĐI", "5AJ": "GIẾT ANH TA" },
  "SS16": { "R3": "NÓI VỀ MẸ", "3Vx": "QUAY LẠI" },
  "SS17": { "R4": "THEO COLIN", "3Vx": "QUAY LẠI" },
  "1S": { "3B": "NÉM TRÀ VÀO MÁY TÍNH", "3C": "LA MẮNG BỐ" },
  "SS18": { "3Vx": "QUAY LẠI" },
  "1R": { "3B": "NÉM TRÀ VÀO MÁY TÍNH", "3C": "LA MẮNG BỐ" },
  "SS19": { "R3": "NÓI VỀ MẸ", "3Nx": "QUAY LẠI" },
  "Z62b": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "Z62a": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "2Bt1": { "No": "KHÔNG", "3B": "NÉM TRÀ VÀO MÁY TÍNH", "3C": "LA MẮNG BỐ" },
  "3Vfs": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "SS10": { "1PA": "QUAY LẠI" },
  "SS11": { "nsg-SS11-0": "LÀM VIỆC TẠI TUCKERSOFT?", "3Ax": "QUAY LẠI" },
  "SS12": { "R3": "NÓI VỀ MẸ", "3Ax": "QUAY LẠI" },
  "SS13": { "3Ax": "QUAY LẠI" },
  "SS14": { "R3": "NÓI VỀ MẸ", "nsg-SS14-1": "QUAY LẠI" },
  "SS15": { "R4": "THEO COLIN", "nsg-SS15-1": "QUAY LẠI" },
  "3Nx": { "8L": "STEFAN", "3Q": "COLIN" },
  "2B": { "No": "KHÔNG", "1R": "PHAEDRA", "1S": "TAM GIÁC BERMUDA" },
  "S35B": { "nsg-WhoThereChoice": "AI ĐÓ VẬY?", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "2Gp1": { "3B": "NÉM TRÀ VÀO MÁY TÍNH", "3C": "LA MẮNG BỐ" },
  "3AH2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3Wbs": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "1HB": { "nsg-8AChoice": "CHẤP NHẬN", "nsg-1Q_rewatch": "TỪ CHỐI" },
  "3AH1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "S59A": { "nsg-S59A-0": "CHẶT HAY CHÔN?", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "S59B": { "nsg-S59B-0": "CHẶT HAY CHÔN?", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "S35A": { "nsg-WhoThereChoice": "AI ĐÓ VẬY?", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "5A": { "5H": "GIẾT BỐ", "5G": "THÔI ĐI" },
  "5QA": { "5UA": "CÓ", "5TA": "KHÔNG" },
  "1QA": { "3B": "NÉM TRÀ VÀO MÁY TÍNH", "3C": "LA MẮNG BỐ" },
  "8JB1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "S34A": { "R4": "THEO COLIN", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "3N": { "8L": "STEFAN", "3Q": "COLIN" },
  "8JB2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "S34B": { "R4": "THEO COLIN", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "1Qtt": { "nsg-2BChoice": "CÓ", "2GA": "KHÔNG" },
  "3M": { "3N": "CÓ", "3P": "KHÔNG" },
  "3L": { "nsg-VisitHaynesChoice": "GẶP BÁC SĨ HAYNES", "nsg-FollowColinChoice": "THEO COLIN" },
  "3J": { "nsg-VisitHaynesChoice": "GẶP BÁC SĨ HAYNES", "nsg-FollowColinChoice": "THEO COLIN" },
  "5AD": { "5AF": "KHÔNG BIẾT", "5AE": "ANH TA NHẢY" },
  "3R": { "3U": "CẮN MÓNG TAY", "3T": "KÉO TAI" },
  "3P": { "8L": "STEFAN", "3Q": "COLIN" },
  "3Z": { "nsg-FamilyPhotoChoice": "NHẶT ẢNH GIA ĐÌNH", "nsg-BookChoice": "NHẶT QUYỂN SÁCH" },
  "3X": { "8B_Variant2": "LẤY CHÚNG", "nsg-FlushThemChoice3X": "THẢI XUỐNG BỒN" },
  "3VA": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "3Wbf": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "ZK1": { "8J": "ĐỒ CHƠI", "nsg-PAXChoice": "PAX" },
  "ZK2": { "nsg-PAXChoice": "PAX", "nsg-PACStudyChoice": "PAC" },
  "5AG": { "5AH": "ĐỂ ANH TA ĐI", "5AJ": "GIẾT ANH TA" },
  "ZK3": { "8J": "ĐỒ CHƠI", "nsg-PACStudyChoice": "PAC" },
  "3VB": { "nsg-FamilyPhotoChoice": "NHẶT ẢNH GIA ĐÌNH", "nsg-BookChoice": "NHẶT QUYỂN SÁCH" },
  "3AB2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3AB1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "2Bt2": { "No": "KHÔNG" },
  "3AJ2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3AJ1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "S37A": { "R2": "LẤY THỎ TỪ BỐ", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "S37B": { "R2": "LẤY THỎ TỪ BỐ", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "5AD2": { "5AF": "KHÔNG BIẾT", "5AE": "ANH TA NHẢY" },
  "3Xxc": { "8B": "VỨT CHÚNG ĐI", "nsg-FlushThemChoice3X": "THẢI XUỐNG BỒN" },
  "7B": { "7C": "KỂ THÊM CHO ANH TA", "7D": "DỪNG CUỘC TRÒ CHUYỆN" },
  "7A": { "7B": "KỂ THÊM", "7B2": "CỐ GIẢI THÍCH" },
  "3Xxa": { "8B_Variant2": "LẤY CHÚNG", "nsg-FlushThemChoice3X": "THẢI XUỐNG BỒN" },
  "3Ax": { "3B": "NÉM TRÀ VÀO MÁY TÍNH", "3C": "LA MẮNG BỐ" },
  "3AK1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "7H": { "7K": "CHẶT TAY BỐ", "7J": "ĐÁ HẠ BỘ" },
  "5Q": { "5U": "CÓ", "5T": "KHÔNG" },
  "SS7": { "R1": "NHẶT ẢNH", "5H": "GIẾT BỐ" },
  "SS8": { "R2": "LẤY THỎ TỪ BỐ", "5H": "GIẾT BỐ" },
  "SS9": { "R4": "THEO COLIN", "5H": "GIẾT BỐ" },
  "SS3": { "R2": "LẤY THỎ TỪ BỐ", "nsg-WhoThereChoice": "AI ĐÓ VẬY?" },
  "SS4": { "R4": "THEO COLIN", "nsg-WhoThereChoice": "AI ĐÓ VẬY?" },
  "SS5": { "nsg-WhoThereChoice": "AI ĐÓ VẬY?" },
  "SS6": { "R3": "NÓI VỀ MẸ", "5H": "GIẾT BỐ" },
  "1GB": { "nsg-8AChoice": "CHẤP NHẬN", "nsg-1Q_rewatch": "TỪ CHỐI" },
  "SS1": { "R3": "NÓI VỀ MẸ", "R4": "THEO COLIN" },
  "1GA": { "nsg-8AChoice": "CHẤP NHẬN", "nsg-1Q_rewatch": "TỪ CHỐI" },
  "5V": { "nsg-5V-0": "CHÔN XÁC", "nsg-5V-1": "CHẶT XÁC" },
  "SS2": { "R1": "NHẶT ẢNH", "nsg-WhoThereChoice": "AI ĐÓ VẬY?" },
  "S36A": { "R1": "NHẶT ẢNH", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "S36B": { "R1": "NHẶT ẢNH", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "SS52": { "nsg-SS52-0": "CHẶT HAY CHÔN?", "0cr2": "THOÁT VỀ PHẦN KẾT" },
  "SS53": { "nsg-SS53-0": "CHẶT HAY CHÔN?", "0cr2": "THOÁT VỀ PHẦN KẾT" },
  "SS54": { "nsg-WhoThereChoice-SS54": "AI ĐÓ VẬY?", "0cr2": "THOÁT VỀ PHẦN KẾT" },
  "SS55": { "nsg-SS55-0": "NHẶT ẢNH", "0cr2": "THOÁT VỀ PHẦN KẾT" },
  "1HA": { "nsg-8AChoice": "CHẤP NHẬN", "nsg-1Q_rewatch": "TỪ CHỐI" },
  "SS56": { "nsg-SS56-0": "LẤY THỎ TỪ BỐ", "0cr2": "THOÁT VỀ PHẦN KẾT" },
  "3Vbs": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "SS57": { "R6": "'CHƯƠNG TRÌNH & KIỂM SOÁT'", "0cr2": "THOÁT VỀ PHẦN KẾT" },
  "3Vbf": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "1PA": { "nsg-8AChoice": "CHẤP NHẬN", "nsg-1Q_rewatch": "TỪ CHỐI" },
  "1Qnw": { "nsg-2BChoice": "CÓ", "2GA": "KHÔNG" },
  "Z4cd": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "SS50": { "nsg-SS50-0": "NÓI VỀ MẸ", "0cr2": "THOÁT VỀ PHẦN KẾT" },
  "SS51": { "nsg-SS51-0": "THEO COLIN", "0cr2": "THOÁT VỀ PHẦN KẾT" },
  "Z61e": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3AD3": { "8J": "ĐỒ CHƠI", "nsg-PACStudyChoice": "PAC" },
  "Z61d": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "Z4": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "Z61c": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "Z61b": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "Z1": { "3B": "NÉM TRÀ VÀO MÁY TÍNH", "3C": "LA MẮNG BỐ" },
  "Z61f": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "Z61a": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3AD2": { "nsg-PAXChoice": "PAX", "nsg-PACStudyChoice": "PAC" },
  "3AD1": { "8J": "ĐỒ CHƠI", "nsg-PAXChoice": "PAX" },
  "ZE": { "nsg-FamilyPhotoChoice": "NHẶT ẢNH GIA ĐÌNH", "nsg-BookChoice": "NHẶT QUYỂN SÁCH" },
  "ZD": { "nsg-FamilyPhotoChoice": "NHẶT ẢNH GIA ĐÌNH", "nsg-BookChoice": "NHẶT QUYỂN SÁCH" },
  "4C2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "ZB": { "nsg-2BChoice": "CÓ", "2GA": "KHÔNG" },
  "1E": { "1H": "THOMPSON TWINS", "1G": "NOW 2" },
  "3Xac": { "nsg-ThrowThemChoice": "VỨTCHÚNG ĐI", "nsg-FlushThemChoice3X": "THẢI XUỐNG BỒN" },
  "1D": { "1H": "THOMPSON TWINS", "1G": "NOW 2" },
  "3Xa": { "8B_Variant2": "LẤY CHÚNG", "nsg-FlushThemChoice3X": "THẢI XUỐNG BỒN" },
  "ZK": { "nsg-JFDChoice": "JFD", "nsg-PAXChoice": "PAX" },
  "1A": { "1E": "SUGAR PUFFS", "1D": "FROSTIES" },
  "4C1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "ZJ": { "nsg-FamilyPhotoChoice": "NHẶT ẢNH GIA ĐÌNH", "nsg-BookChoice": "NHẶT QUYỂN SÁCH" },
  "ZH": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "ZG": { "8L": "STEFAN", "3Q": "COLIN" },
  "3AD": { "nsg-JFDChoice": "JFD", "nsg-PAXChoice": "PAX" },
  "3AC2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3AC": { "nsg-ThrowTeaChoice": "NÉM TRÀ VÀO MÁY TÍNH", "nsg-DestroyComputerChoice": "PHÁ MÁY TÍNH" },
  "3AB": { "nsg-ThrowTeaChoice": "NÉM TRÀ VÀO MÁY TÍNH", "nsg-DestroyComputerChoice": "PHÁ MÁY TÍNH" },
  "ZHw6": { "nsg-FamilyPhotoChoice": "NHẶT ẢNH GIA ĐÌNH", "nsg-BookChoice": "NHẶT QUYỂN SÁCH" },
  "3AH": { "nsg-ThrowTeaChoice": "NÉM TRÀ VÀO MÁY TÍNH", "nsg-DestroyComputerChoice": "PHÁ MÁY TÍNH" },
  "3Wff": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "3AF": { "nsg-ThrowTeaChoice": "NÉM TRÀ VÀO MÁY TÍNH", "nsg-DestroyComputerChoice": "PHÁ MÁY TÍNH" },
  "3AK2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "2GA": { "nsg-2BChoice": "CÓ", "nsg-2GChoice": "KHÔNG" },
  "S38A": { "R6": "'CHƯƠNG TRÌNH & KIỂM SOÁT'", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "S38B": { "R6": "'CHƯƠNG TRÌNH & KIỂM SOÁT'", "0cr1": "THOÁT VỀ PHẦN KẾT" },
  "3AC1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "2Gt1": { "3B": "NÉM TRÀ VÀO MÁY TÍNH", "3C": "LA MẮNG BỐ" },
  "3AL2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3Wfs": { "3Y": "PHÁ MÁY TÍNH", "3Z": "ĐẬP BÀN" },
  "3AL1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "3AL": { "nsg-ThrowTeaChoice": "NÉM TRÀ VÀO MÁY TÍNH", "nsg-DestroyComputerChoice": "PHÁ MÁY TÍNH" },
  "3AK": { "nsg-ThrowTeaChoice": "NÉM TRÀ VÀO MÁY TÍNH", "nsg-DestroyComputerChoice": "PHÁ MÁY TÍNH" },
  "8K": { "nsg-8K-0": "NÉM TRÀ VÀO MÁY TÍNH", "nsg-8K-1": "PHÁ MÁY TÍNH" },
  "3AJ": { "nsg-ThrowTeaChoice": "NÉM TRÀ VÀO MÁY TÍNH", "nsg-DestroyComputerChoice": "PHÁ MÁY TÍNH" },
  "8J": { "8JA": "CÓ", "nsg-8J-1": "KHÔNG" },
  "4D2": { "7A": "CHỮ 'N' NETFLIX", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "4D1": { "nsg-LettersPACSChoice": "P.A.C.S.", "nsg-WhiteBearChoice": "KÝ HIỆU 'WHITE BEAR'" },
  "5VA": { "nsg-5V-0": "CHÔN XÁC", "nsg-5V-1": "CHẶT XÁC" },
};

/** Look up Vietnamese text for a choice. Falls back to the choiceId itself. */
export function getViText(segmentId: string, choiceId: string): string {
  return VI[segmentId]?.[choiceId] ?? choiceId;
}
